import React, { useState, useRef } from 'react';
import { uploadToImgBB } from '../../utils/imgbbService';
import { compressImage } from '../../utils/imageCompressor';
import LoadingSpinner from './LoadingSpinner';
import { motion, AnimatePresence } from 'framer-motion';
import LightroomEditorStudio from '../editor/LightroomEditorStudio';
import { UploadStepTracker } from './UploadStepTracker';

export interface DirectImageUrlInputProps {
    value: string;
    onChange: (url: string) => void;
    label?: string;
    placeholder?: string;
    className?: string;
    disabled?: boolean;
    required?: boolean;
    id?: string;
    name?: string;
    helperText?: string;
    previewAspectRatio?: 'square' | 'cover' | 'auto';
    showPreview?: boolean;
}

export const DirectImageUrlInput: React.FC<DirectImageUrlInputProps> = ({
    value,
    onChange,
    label = "Direct Image / GIF URL",
    placeholder = "https://i.ibb.co/example/animated.gif or click '⚡ Upload GIF/Image' to generate...",
    className = "",
    disabled = false,
    required = false,
    id,
    name,
    helperText = "✨ Supports Animated GIFs (.gif), PNG, JPG, & WEBP! Click '⚡ Upload GIF/Image' or drag & drop a file here to automatically generate a direct ImgBB URL and auto-fill the box instantly!",
    previewAspectRatio = 'auto',
    showPreview = true
}) => {
    const [isUploading, setIsUploading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [successMsg, setSuccessMsg] = useState<string | null>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [imageLoadError, setImageLoadError] = useState(false);
    const [isEditorOpen, setIsEditorOpen] = useState(false);
    const [currentStep, setCurrentStep] = useState<number>(0);
    const [originalSize, setOriginalSize] = useState<number | undefined>(undefined);
    const [compressedSize, setCompressedSize] = useState<number | undefined>(undefined);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileUpload = async (file: File) => {
        if (!file) return;
        if (!file.type.startsWith('image/')) {
            setError("❌ Please select a valid image or animated GIF file (GIF, PNG, JPG, WEBP).");
            return;
        }

        setIsUploading(true);
        setError(null);
        setSuccessMsg(null);
        setImageLoadError(false);
        setCurrentStep(1); // 1. Compressing image resolution & size
        setOriginalSize(file.size);
        setCompressedSize(undefined);

        await new Promise(r => setTimeout(r, 250));

        try {
            let fileToUpload = file;
            const isGif = file.type === 'image/gif' || file.name.toLowerCase().endsWith('.gif');
            
            setCurrentStep(2); // 2. Converting to lightweight WebP
            await new Promise(r => setTimeout(r, 250));

            // Auto-compress non-GIF images to lightweight WebP before uploading for super fast loading!
            if (!isGif && file.size > 50 * 1024) {
                try {
                    const res = await compressImage(file, { quality: 0.82, maxWidth: 1920, maxHeight: 1920, targetFormat: 'image/webp' });
                    fileToUpload = res.file;
                    setCompressedSize(res.compressedSize);
                } catch (err) {
                    console.warn("Auto-compression skipped, uploading original:", err);
                    setCompressedSize(file.size);
                }
            } else {
                setCompressedSize(file.size);
            }

            setCurrentStep(3); // 3. Uploading optimized file to ImgBB Cloud
            const cleanName = fileToUpload.name.replace(/[^a-zA-Z0-9.-]/g, '_');
            const result = await uploadToImgBB(fileToUpload, cleanName);
            
            if (result.error || !result.url) {
                throw new Error(result.error || "Failed to generate direct image URL from ImgBB.");
            }

            setCurrentStep(4); // 4. Generating Direct URL
            await new Promise(r => setTimeout(r, 300));

            setCurrentStep(5); // 5. Ready! URL auto-filled automatically!
            // Automatically set the URL in the input box!
            onChange(result.url);
            if (isGif) {
                setSuccessMsg("✨ Animated GIF Direct URL generated by ImgBB & auto-filled into box!");
            } else {
                setSuccessMsg("✨ Direct WebP Image URL generated & auto-filled!");
            }
            setTimeout(() => {
                setSuccessMsg(null);
                setCurrentStep(0);
            }, 6000);
        } catch (err: any) {
            setError(err.message || "Upload failed. Please check your internet connection.");
            setCurrentStep(0);
        } finally {
            setIsUploading(false);
            if (fileInputRef.current) {
                fileInputRef.current.value = "";
            }
        }
    };

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) handleFileUpload(file);
    };

    const handleDragOver = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        if (!disabled && !isUploading) setIsDragging(true);
    };

    const handleDragLeave = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setIsDragging(false);
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setIsDragging(false);
        if (disabled || isUploading) return;

        const file = e.dataTransfer.files?.[0];
        if (file) handleFileUpload(file);
    };

    // Calculate aspect ratio styling for preview
    const previewShapeClasses = 
        previewAspectRatio === 'square' ? 'w-24 h-24 sm:w-28 sm:h-28 rounded-full object-cover border-2 border-indigo-500/50 shadow-md' :
        previewAspectRatio === 'cover' ? 'w-full h-32 sm:h-40 rounded-xl object-cover border border-gray-300 dark:border-gray-700 shadow-md' :
        'max-h-48 max-w-full rounded-lg object-contain bg-black/5 dark:bg-white/5 border border-gray-200 dark:border-gray-800 p-1';

    return (
        <div className={`w-full space-y-2 ${className}`}>
            {/* Label & Helper */}
            {label && (
                <div className="flex items-center justify-between flex-wrap gap-1">
                    <label htmlFor={id} className="block text-sm font-semibold text-[var(--theme-text)]">
                        {label} {required && <span className="text-red-500">*</span>}
                    </label>
                    <div className="flex items-center gap-1.5">
                        <span className="text-[11px] font-bold px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20 flex items-center gap-1">
                            <span>🎞️</span>
                            <span>GIF Auto-URL</span>
                        </span>
                        <span className="text-[11px] font-bold px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-500 border border-indigo-500/20">
                            ⚡ ImgBB v1
                        </span>
                    </div>
                </div>
            )}

            {/* Hidden File Input */}
            <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept="image/*"
                className="hidden"
                disabled={disabled || isUploading}
            />

            {/* Input Row + Side Upload Option */}
            <div 
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`flex flex-col sm:flex-row items-stretch gap-2 transition-all rounded-xl p-1.5 ${
                    isDragging ? 'bg-indigo-500/10 ring-2 ring-indigo-500 border-dashed border-2 border-indigo-400' : ''
                }`}
            >
                {/* Direct URL Text Input */}
                <div className="relative flex-1">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                        <span>🔗</span>
                    </div>
                    <input
                        type="url"
                        id={id}
                        name={name}
                        value={value}
                        onChange={(e) => {
                            onChange(e.target.value);
                            setImageLoadError(false);
                        }}
                        placeholder={placeholder}
                        disabled={disabled || isUploading}
                        required={required}
                        className="w-full pl-9 pr-8 py-2.5 bg-[var(--theme-card-bg-alt)] border border-gray-300 dark:border-gray-700 rounded-xl text-sm text-[var(--theme-text)] placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all disabled:opacity-60"
                    />
                    {value && !disabled && (
                        <button
                            type="button"
                            onClick={() => {
                                onChange('');
                                setImageLoadError(false);
                            }}
                            className="absolute inset-y-0 right-0 pr-2.5 flex items-center text-gray-400 hover:text-red-500 transition-colors"
                            title="Clear URL"
                        >
                            ✕
                        </button>
                    )}
                </div>

                {/* Side Option: Upload Image to Generate Direct URL */}
                <motion.button
                    type="button"
                    whileHover={!disabled && !isUploading ? { scale: 1.02 } : {}}
                    whileTap={!disabled && !isUploading ? { scale: 0.98 } : {}}
                    onClick={() => fileInputRef.current?.click()}
                    disabled={disabled || isUploading}
                    className={`px-3.5 py-2.5 rounded-xl text-xs sm:text-sm font-bold shadow-md flex items-center justify-center space-x-1.5 transition-all whitespace-nowrap ${
                        isUploading 
                            ? 'bg-amber-500 text-white cursor-wait animate-pulse' 
                            : 'bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white hover:shadow-lg shadow-indigo-500/20'
                    } disabled:opacity-50`}
                    title="Upload a GIF or image from device; automatically generates and inserts Direct ImgBB URL"
                >
                    {isUploading ? (
                        <>
                            <LoadingSpinner size="sm" />
                            <span>Generating URL...</span>
                        </>
                    ) : (
                        <>
                            <span className="text-base animate-pulse">⚡</span>
                            <span>Upload GIF/Image</span>
                        </>
                    )}
                </motion.button>

                {/* Edit Studio Button */}
                <motion.button
                    type="button"
                    whileHover={!disabled && !isUploading ? { scale: 1.02 } : {}}
                    whileTap={!disabled && !isUploading ? { scale: 0.98 } : {}}
                    onClick={() => setIsEditorOpen(true)}
                    disabled={disabled || isUploading}
                    className="px-3 py-2.5 rounded-xl text-xs sm:text-sm font-bold shadow-md flex items-center justify-center space-x-1.5 transition-all whitespace-nowrap bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white hover:shadow-lg disabled:opacity-50"
                    title="Open Image Editor Studio to crop, rotate, or apply aesthetic filters"
                >
                    <span className="text-base">🎨</span>
                    <span>Edit & Craft</span>
                </motion.button>
            </div>

            {/* Helper text or feedback messages */}
            <div className="flex flex-wrap items-center justify-between text-xs px-1 gap-2">
                <span className="text-[var(--theme-text-secondary)] text-[11px] flex-1">{helperText}</span>
                {isDragging && <span className="text-indigo-500 font-bold animate-bounce">📥 Drop GIF / image here to generate direct URL!</span>}
            </div>

            {error && (
                <div className="p-2.5 rounded-lg bg-red-500/10 border border-red-500/30 text-red-600 dark:text-red-400 text-xs font-semibold flex items-center space-x-2">
                    <span>⚠️</span>
                    <span>{error}</span>
                </div>
            )}

            {successMsg && (
                <div className="p-2 rounded-lg bg-green-500/10 border border-green-500/30 text-green-600 dark:text-green-400 text-xs font-bold flex items-center space-x-2 animate-fadeIn">
                    <span>✅</span>
                    <span>{successMsg}</span>
                </div>
            )}

            <UploadStepTracker currentStep={currentStep} originalSize={originalSize} compressedSize={compressedSize} error={error} />

            {/* Live Image Preview */}
            {showPreview && value && (
                <AnimatePresence>
                    <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="mt-2 p-3 bg-[var(--theme-card-bg-alt)]/60 border border-gray-200/50 dark:border-gray-700/50 rounded-xl flex flex-col sm:flex-row items-center gap-4"
                    >
                        <div className="flex-shrink-0 flex items-center justify-center">
                            {!imageLoadError ? (
                                <img
                                    src={value}
                                    alt="Live Preview"
                                    onError={() => setImageLoadError(true)}
                                    className={`transition-all duration-300 ${previewShapeClasses}`}
                                />
                            ) : (
                                <div className="w-24 h-24 rounded-lg bg-red-500/10 border border-red-500/30 flex flex-col items-center justify-center p-2 text-center text-red-500 text-xs font-semibold">
                                    <span>❌</span>
                                    <span>Invalid Image URL</span>
                                </div>
                            )}
                        </div>
                        <div className="flex-1 text-center sm:text-left min-w-0">
                            <p className="text-xs font-bold text-[var(--theme-text)] uppercase tracking-wider flex items-center justify-center sm:justify-start gap-1.5">
                                {value.toLowerCase().includes('.gif') || value.toLowerCase().includes('gif') ? (
                                    <>
                                        <span>🎞️ Live Animated GIF Preview</span>
                                        <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-purple-500/20 text-purple-600 dark:text-purple-400 border border-purple-500/30">✨ Animated GIF</span>
                                    </>
                                ) : (
                                    <>
                                        <span>🖼️ Live Image Preview</span>
                                        <span className="text-[10px] font-normal px-1.5 py-0.5 rounded bg-green-500/20 text-green-600 dark:text-green-400">Active</span>
                                    </>
                                )}
                            </p>
                            <p className="text-[11px] text-[var(--theme-text-secondary)] mt-1 truncate font-mono bg-black/5 dark:bg-white/5 p-1.5 rounded border border-gray-200/40 dark:border-gray-800/40">
                                {value}
                            </p>
                            <div className="mt-2 flex flex-wrap items-center justify-center sm:justify-start gap-2">
                                <button
                                    type="button"
                                    onClick={() => setIsEditorOpen(true)}
                                    className="text-[11px] font-bold px-2.5 py-1 rounded-lg bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/40 text-purple-400 hover:text-purple-300 hover:border-purple-400 transition-all flex items-center gap-1"
                                >
                                    <span>🎨 Edit This Photo</span>
                                </button>
                                <span className="text-gray-300 dark:text-gray-700">|</span>
                                <a
                                    href={value}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-[11px] font-semibold text-indigo-500 hover:text-indigo-600 underline flex items-center gap-1"
                                >
                                    <span>↗️ Open</span>
                                </a>
                                <span className="text-gray-300 dark:text-gray-700">|</span>
                                <button
                                    type="button"
                                    onClick={() => {
                                        navigator.clipboard.writeText(value);
                                        setSuccessMsg("📋 URL Copied!");
                                        setTimeout(() => setSuccessMsg(null), 3000);
                                    }}
                                    className="text-[11px] font-semibold text-[var(--theme-text-secondary)] hover:text-[var(--theme-text)] transition-colors"
                                >
                                    📋 Copy
                                </button>
                            </div>
                        </div>
                    </motion.div>
                </AnimatePresence>
            )}

            {/* Embedded Lightroom Studio Modal Overlay */}
            <AnimatePresence>
                {isEditorOpen && (
                    <div className="fixed inset-0 z-[99999] bg-black/90 backdrop-blur-2xl flex flex-col">
                        <LightroomEditorStudio
                            onBack={() => setIsEditorOpen(false)}
                            initialImageUrl={value || ''}
                            onSave={(newUrl) => {
                                onChange(newUrl);
                                setIsEditorOpen(false);
                                setSuccessMsg("✨ Edited photo saved & URL updated automatically!");
                                setTimeout(() => setSuccessMsg(null), 4000);
                            }}
                        />
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
};
